# Generated by Django 3.1.2 on 2021-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='title',
            field=models.CharField(default='Dataset 1488', max_length=100),
        ),
    ]
