# Generated by Django 3.1.2 on 2021-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_manager', '0002_auto_20210505_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csvs'),
        ),
    ]
